# Explainable Swin-UNETR Framework for Automated Lumbar Spine Disease Detection and Classification from MRI Images

## Notebook 1 – Dataset Overview

**Dataset:** RSNA Lumbar Spine Degenerative Classification

---

## Purpose of this Notebook

This notebook introduces the RSNA Lumbar Spine Degenerative Classification dataset. It explores the dataset structure, metadata, MRI image organization, and annotation files. The notebook serves as the foundation for subsequent preprocessing, exploratory data analysis (EDA), and Swin UNETR model development.

## Objectives

The objectives of this notebook are:

1. Understand the dataset structure.
2. Load the annotation CSV files.
3. Explore MRI image folders.
4. Count the total number of patients.
5. Count MRI series and slices.
6. Verify annotation files.
7. Prepare the dataset for exploratory data analysis.

In [23]:
# ============================================================
# Import Required Libraries
# ============================================================

import os
import glob
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import pydicom

warnings.filterwarnings("ignore")

## Import Libraries

The following libraries are required:

- **os** – File and folder operations
- **glob** – Search files recursively
- **NumPy** – Numerical computations
- **Pandas** – Reading and manipulating CSV files
- **Matplotlib** – Data visualization
- **PyDICOM** – Reading MRI DICOM images

In [24]:
# ============================================================
# Dataset Path
# ============================================================

dataset_path = r"D:\Msc Major Project Swin Unetr Framework\MSc_SwinUNETR_Project\dataset\rsna-2024-lumbar-spine-degenerative-classification"

print("Dataset Path:")
print(dataset_path)

Dataset Path:
D:\Msc Major Project Swin Unetr Framework\MSc_SwinUNETR_Project\dataset\rsna-2024-lumbar-spine-degenerative-classification

In [25]:

# ============================================================
# Verify Dataset
# ============================================================

if os.path.exists(dataset_path):
    print("Dataset found successfully.")
else:
    print("Dataset path does not exist.")

Dataset found successfully.

In [26]:
# ============================================================
# Display Folder Contents
# ============================================================

files = sorted(os.listdir(dataset_path))

print("Files and folders inside dataset:\n")

for item in files:
    print(item)

Files and folders inside dataset:

sample_submission.csv
test_images
test_series_descriptions.csv
train.csv
train_images
train_label_coordinates.csv
train_series_descriptions.csv

In [27]:
# ============================================================
# Load CSV Files
# ============================================================

train_df = pd.read_csv(
    os.path.join(dataset_path, "train.csv")
)

series_df = pd.read_csv(
    os.path.join(dataset_path, "train_series_descriptions.csv")
)

coord_df = pd.read_csv(
    os.path.join(dataset_path, "train_label_coordinates.csv")
)

In [28]:
# ============================================================
# Dataset Shapes
# ============================================================

print("Train CSV Shape:")
print(train_df.shape)

print("\nSeries CSV Shape:")
print(series_df.shape)

print("\nCoordinate CSV Shape:")
print(coord_df.shape)

Train CSV Shape:
(1975, 26)

Series CSV Shape:
(6294, 3)

Coordinate CSV Shape:
(48692, 7)

In [29]:
# ============================================================
# Display First Five Rows
# ============================================================

display(train_df.head())

display(series_df.head())

display(coord_df.head())

,study_id,spinal_canal_stenosis_l1_l2,spinal_canal_stenosis_l2_l3,spinal_canal_stenosis_l3_l4,spinal_canal_stenosis_l4_l5,spinal_canal_stenosis_l5_s1,left_neural_foraminal_narrowing_l1_l2,left_neural_foraminal_narrowing_l2_l3,left_neural_foraminal_narrowing_l3_l4,left_neural_foraminal_narrowing_l4_l5,...,left_subarticular_stenosis_l1_l2,left_subarticular_stenosis_l2_l3,left_subarticular_stenosis_l3_l4,left_subarticular_stenosis_l4_l5,left_subarticular_stenosis_l5_s1,right_subarticular_stenosis_l1_l2,right_subarticular_stenosis_l2_l3,right_subarticular_stenosis_l3_l4,right_subarticular_stenosis_l4_l5,right_subarticular_stenosis_l5_s1
0,4003253,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
1,4646740,Normal/Mild,Normal/Mild,Moderate,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Moderate,Moderate,Moderate,Normal/Mild
2,7143189,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
3,8785691,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
4,10728036,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild

   study_id   series_id series_description
0   4003253   702807833   Sagittal T2/STIR
1   4003253  1054713880        Sagittal T1
2   4003253  2448190387           Axial T2
3   4646740  3201256954           Axial T2
4   4646740  3486248476        Sagittal T1

,study_id,series_id,instance_number,condition,level,x,y
0,4003253,702807833,8,Spinal Canal Stenosis,L1/L2,322.831858,227.964602
1,4003253,702807833,8,Spinal Canal Stenosis,L2/L3,320.571429,295.714286
2,4003253,702807833,8,Spinal Canal Stenosis,L3/L4,323.030303,371.818182
3,4003253,702807833,8,Spinal Canal Stenosis,L4/L5,335.292035,427.327434
4,4003253,702807833,8,Spinal Canal Stenosis,L5/S1,353.415929,483.964602

In [30]:
# ============================================================
# Basic Statistics
# ============================================================

print("Number of Patients :", train_df.shape[0])

print("Number of Disease Columns :", train_df.shape[1]-1)

print("Number of MRI Series :", len(series_df))

print("Number of Coordinate Labels :", len(coord_df))

Number of Patients : 1975
Number of Disease Columns : 25
Number of MRI Series : 6294
Number of Coordinate Labels : 48692

In [31]:
# ============================================================
# Display Column Names
# ============================================================

print("Train.csv Columns\n")

for column in train_df.columns:
    print(column)

Train.csv Columns

study_id
spinal_canal_stenosis_l1_l2
spinal_canal_stenosis_l2_l3
spinal_canal_stenosis_l3_l4
spinal_canal_stenosis_l4_l5
spinal_canal_stenosis_l5_s1
left_neural_foraminal_narrowing_l1_l2
left_neural_foraminal_narrowing_l2_l3
left_neural_foraminal_narrowing_l3_l4
left_neural_foraminal_narrowing_l4_l5
left_neural_foraminal_narrowing_l5_s1
right_neural_foraminal_narrowing_l1_l2
right_neural_foraminal_narrowing_l2_l3
right_neural_foraminal_narrowing_l3_l4
right_neural_foraminal_narrowing_l4_l5
right_neural_foraminal_narrowing_l5_s1
left_subarticular_stenosis_l1_l2
left_subarticular_stenosis_l2_l3
left_subarticular_stenosis_l3_l4
left_subarticular_stenosis_l4_l5
left_subarticular_stenosis_l5_s1
right_subarticular_stenosis_l1_l2
right_subarticular_stenosis_l2_l3
right_subarticular_stenosis_l3_l4
right_subarticular_stenosis_l4_l5
right_subarticular_stenosis_l5_s1

## Summary

In this notebook:

- The RSNA dataset was successfully loaded.
- The folder structure was verified.
- Annotation CSV files were imported.
- Dataset dimensions were explored.
- The disease label columns were identified.

The next notebook will perform an in-depth Exploratory Data Analysis (EDA), including disease distribution, MRI sequence analysis, and class balance.